"""
Central place for paths and constants used across the project.

Keeping these in one file means every other module (loader, chunker,
vectorstore, query) agrees on where things live without hardcoding
paths in multiple places.
"""

from pathlib import Path

# Project root = the folder this file's parent (app/) lives in.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Where you drop downloaded 10-K filings (see README for the folder layout).
DATA_DIR = PROJECT_ROOT / "data"

# Where Chroma persists its local vector database. This folder is
# generated by the ingest script, not checked into git.
CHROMA_DIR = PROJECT_ROOT / "chroma_db"

# Name of the Chroma collection all filings are stored in.
COLLECTION_NAME = "sec_10k_filings"

# The section labels we chunk documents by, instead of splitting on
# arbitrary character/token counts. Each maps to the "Item N" label SEC
# filings use, so loader.py can find the right header in the filing.
SECTION_ITEM_MAP = {
    "Business": "1",
    "Risk Factors": "1A",
    "MD&A": "7",
    "Financial Statements": "8",
}
SECTIONS = list(SECTION_ITEM_MAP.keys())

# Chunking targets, in characters (roughly 4 chars/token, so ~1500 chars
# is ~350-400 tokens — a reasonable size for embedding while still being
# specific enough to cite). CHUNK_OVERLAP carries a bit of the previous
# chunk's tail into the next one, so a fact split across a chunk boundary
# still has surrounding context in at least one of the two chunks.
CHUNK_SIZE_CHARS = 1500
CHUNK_OVERLAP_CHARS = 200
